language: objective-c
osx_image: xcode9.2
env:
  global:
  - WORKSPACE=Cacher.xcworkspace
  - IOS_FRAMEWORK_SCHEME="Cacher"
  - IOS_SDK=iphonesimulator11.2
  - TVOS_FRAMEWORK_SCHEME="Cacher-tvOS"
  - TVOS_SDK=appletvsimulator11.2

  matrix:
    - DESTINATION="OS=11.2,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"    EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=11.2,name=Apple TV"    SCHEME="$TVOS_FRAMEWORK_SCHEME"     SDK="$TVOS_SDK"    EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;

after_success:
  - bash <(curl -s https://codecov.io/bash) -X xcodeplist
