language: objective-c
osx_image: xcode8
env:
  global:
  - WORKSPACE=Cacher.xcworkspace
  - IOS_FRAMEWORK_SCHEME="Cacher"
  - IOS_SDK=iphonesimulator10.0
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"    EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"
    - DESTINATION="OS=10.0,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"    EXAMPLE_SCHEME="$IOS_EXAMPLE_SCHEME"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
